# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '774caa82259f0da0dc2b07e9594a810e'
  config.secret_key = '1e1ae20d0d32d69c8a362724cb61eb27'
  config.default_from = 'acastelbou1@gmail.com'

end
